version: '3.8'

services:
  website:
    build:
      context: .
      dockerfile: Dockerfile
      target: website
    ports:
      - "4321:4321"
    env_file:
      - .env
    restart: always
    environment:
      - PORT=4321
      - HOST=0.0.0.0

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
      target: dashboard
    ports:
      - "4322:4322"
    env_file:
      - .env
    restart: always
    environment:
      - PORT=4322
      - HOST=0.0.0.0
