import { createEnv } from "@t3-oss/env-core";
import { z } from "zod";

export const env = createEnv({
  server: {
    SERVER_URL: z.string().url().optional(),
    RESEND_API_KEY: z.string().optional(),
    FROM_EMAIL: z.string().optional(),
    REPLY_TO_EMAIL: z.string().optional(),
    LOGTO_ENDPOINT: z.string().url().optional(),
    LOGTO_M2M_APP_ID: z.string().optional(),
    LOGTO_M2M_APP_SECRET: z.string().optional(),
    MXROUTE_EMAIL_DOMAIN: z.string().optional(),
    MXROUTE_EMAIL_OUTBOUND_LIMIT: z.string().optional(),
    MXROUTE_EMAIL_QUOTA: z.string().optional(),
    MXROUTE_LOGIN_KEY: z.string().optional(),
    MXROUTE_SERVER_LOGIN: z.string().optional(),
    MXROUTE_SERVER_URL: z.string().optional(),
    OPENROUTER_API_KEY: z.string().optional(),
    ANTHROPIC_AUTH_TOKEN: z.string().optional(),
    ANTHROPIC_BASE_URL: z.string().url().optional(),
    ANTHROPIC_API_KEY: z.string().optional(),
    CONVEX_SESSION_SECRET: z.string().optional(),
    ALLOWED_FILE_FETCH_HOSTS: z.string().optional(),
  },

  clientPrefix: "VITE_",

  client: {
    VITE_APP_TITLE: z.string().min(1).optional(),
    VITE_CONVEX_URL: z.string().url().optional(),
    VITE_LOGTO_ENDPOINT: z.string().url().optional(),
    VITE_LOGTO_APP_ID: z.string().optional(),
    VITE_LOGTO_REDIRECT_URI: z.string().url().optional(),
    VITE_LOGTO_SCOPES: z.string().optional(),
  },

  runtimeEnv: {
    SERVER_URL: process.env.SERVER_URL,
    RESEND_API_KEY: process.env.RESEND_API_KEY,
    FROM_EMAIL: process.env.FROM_EMAIL,
    REPLY_TO_EMAIL: process.env.REPLY_TO_EMAIL,
    LOGTO_ENDPOINT: process.env.LOGTO_ENDPOINT,
    LOGTO_M2M_APP_ID: process.env.LOGTO_M2M_APP_ID,
    LOGTO_M2M_APP_SECRET: process.env.LOGTO_M2M_APP_SECRET,
    MXROUTE_EMAIL_DOMAIN: process.env.MXROUTE_EMAIL_DOMAIN,
    MXROUTE_EMAIL_OUTBOUND_LIMIT: process.env.MXROUTE_EMAIL_OUTBOUND_LIMIT,
    MXROUTE_EMAIL_QUOTA: process.env.MXROUTE_EMAIL_QUOTA,
    MXROUTE_LOGIN_KEY: process.env.MXROUTE_LOGIN_KEY,
    MXROUTE_SERVER_LOGIN: process.env.MXROUTE_SERVER_LOGIN,
    MXROUTE_SERVER_URL: process.env.MXROUTE_SERVER_URL,
    OPENROUTER_API_KEY: process.env.OPENROUTER_API_KEY,
    ANTHROPIC_AUTH_TOKEN: process.env.ANTHROPIC_AUTH_TOKEN,
    ANTHROPIC_BASE_URL: process.env.ANTHROPIC_BASE_URL,
    ANTHROPIC_API_KEY: process.env.ANTHROPIC_API_KEY,
    CONVEX_SESSION_SECRET: process.env.CONVEX_SESSION_SECRET,
    ALLOWED_FILE_FETCH_HOSTS: process.env.ALLOWED_FILE_FETCH_HOSTS,
    VITE_APP_TITLE: import.meta.env.VITE_APP_TITLE,
    VITE_CONVEX_URL: import.meta.env.VITE_CONVEX_URL,
    VITE_LOGTO_ENDPOINT: import.meta.env.VITE_LOGTO_ENDPOINT,
    VITE_LOGTO_APP_ID: import.meta.env.VITE_LOGTO_APP_ID,
    VITE_LOGTO_REDIRECT_URI: import.meta.env.VITE_LOGTO_REDIRECT_URI,
    VITE_LOGTO_SCOPES: import.meta.env.VITE_LOGTO_SCOPES,
  },
  emptyStringAsUndefined: true,
});
